#!/usr/bin/env bash
# pings any given IP address 5 times
# new bash scripting learnt see man test for more
# $# retrieves length of an arg in CLI
# -eq means equals
# $1 first arg
# fi signals end of if statement

if [$# -eq 0]
then
  echo Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
else
  ping -c 5 "$1"
fi
